# fly.toml app configuration file generated for secure-qrcode on 2023-12-10T16:41:32-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "secure-qrcode"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "60s"
  method = "GET"
  timeout = "5s"
  path = "/healthz"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
