name: Execute lint and tests

on:
  workflow_call:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: sudo apt update && sudo apt install --no-install-recommends -y make git
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cache
          key: self-runner-${{ runner.os }}-python-3.13-${{ hashFiles('uv.lock') }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync --frozen
      - name: pre-commit lint
        run: make lint
      - name: pytest
        run: make test
